# Generated by Django 3.0 on 2021-06-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('device_location', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
