# Generated by Django 3.0 on 2021-06-17 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('company', '0002_auto_20210617_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
