# Generated by Django 3.0 on 2021-06-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0004_auto_20210617_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Membership'),
        ),
    ]
